var answer = answer.concat(
'I don\'t pack well because I don\'t like the garbage that comes from delivery food.',
'Because I can eat fresh food right away.',
'I don\'t order appetizers or desserts seperately.',
'Our country is illegal smoke in side of restaurant.',
'I can barely make simple food like fried eggs or ramen.',
'I am not good at food.',
'I like to eat light food.',
'What can I get you?',
'Follow me to your table, please.',
'I usually eat in restaurants with my wife.',
'I can enjoy enough delicious food within the corporate card limit.',
'Corporate cards have a limit of thrity thousand won per person.',
'Eating out with my boss is a little inconvenient, but essential for my work life.',
'I reserve a lunch restaurant for a meal with my boss.',
'I\'d like to reserve a table at your restaurant next Sunday night.',
'I usually reserve by phone.',
'It is paid for by the company.',
'I have been working for my current company for about eight years.',
'I prefer to be an employee than have my own business.',
'Receiving a salary is more stable than running a business.',
'He wants to book for next Sunday.',
'I haven\'nt thought of running my own restaurant.',
'They have a hard time moving in the plane. <br/><br/>\
They have a struggle moving in the plane.',
'shoulders are heavy.',
'I was planning to go next year, but it seems difficult because I expecting a baby.',
'I took a knife to cut the fruit.',
'I accidentally got on a plane with a knife.',
'설날 means the first day of the new year in the lunar calendar.',
'I don\'t have a winter vacation.',
'It was because the distances of the destinations were a bit far.',
'I traveled for a total of 4 days, 2 days in Gyeongju and 2 days in Busan, and moved from place to place every day.',
'I had a domestic travel.',
'Yes I saw the video.',
'When we notified them about our honeymoon, they prepared wine for us.',
'I\'ve tired both over the phone and online. I prefer online because it\'s cheap.',
'But after calling serveral times, the guesthouse owner canceled it for free.',
'At first, the guesthouse owner did not cancel free of charge and demanded a penalty fee.',
'I wanted a single room, but I accidentally booked a guesthouse and canceled it.',
'At that time, I was too lazy to call, so I just went inside the blanket.',
'The hotel I stayed in when I was on a business trip a few days ago was a bit cold.',
'I think the cleanliness of the hotel is the most important.',
'The travel agency booked both the hotel and the plane.',
'I took a day off to travel to Japan.',
'I need to apply for a vacation to the company to go to Japan.',
'We are going on a package tour, so the travel agency will tafke care of everything.',
'We are ready for the trip.',
'I\'m having trouble sleeping.',
'After this class, I will have breakfast.',
'They provide free breakfast.<br/>\
They offer complimentary breakfast.',
'I went on a business trip and flew a drone.',
'I stayed at a hotel tow days ago.',
'He checks out on Sudnay.',
'I\'m a sociable person, so I like to hang out with other people wherever I go.',
'I want to go to Hawaii for my honeymoon, but I couldn\'t because of my job change schedule.',
'I don\'t speak Japnese at all.',
'When I travel, I don\'t spare money on food.',
'I like Japense ramen the most.',
'I want to eat Japanese food, vist traditonal Japanes tourist spots, and experience Japanes hot springs.',
'My wife wants to go on a pre-birth trip to Japan.',
'I\'m planning to go to Japan on my next vacation. 2 weeks later',
'I\'m not sure, but the price of a hotel in Seoul is about 10 million won per night',
'You can only reserve a double room.',
'I was just busy.',
'The hotel was very clean and satisfactory.',
'When I choose a hotel, price is my top priority, so I don\'t think service is very important.',
'I took classes for 6 days over 2 weeks.',
'I live close to my relatives.',
'I see them every two to three months.',
'get away',
'on tap',
'Because of COVID-19, We couldn\'t go on my honeymoon properly.',
'I remember my trip Thailand on a shor-term misson',
'If I had to choose just one of these, I would like to go to Jeju Island. Because there are various summer tourist attractions here.',
'I have been to Thailand only.',
'What\'s your plan for this summer?',
'I think its\'s better to be far away for a while',
'I wasn\'t able to go abroad on my honeymoon because of COVID-19',
'We first visited traditional attractions',
'No, I don\'t live in Seoul',
'I want to go there and enjoy Leisure activites',
'It can help me get away from work',
'We went on our honeymoon to Gyeongju and Busan',
'I didn\'t live in Jeju Island, I just went for sightseeing',
'Halla Mountain is easy to climb because it has a gentle slope, but the course is very long',
'I have never been to Canada or Mexico <br/>\
I\'ve never set foot in Canada or Mexico',
'My trip to Thailand is very secure',
'I didn\'t visit Hawaii',
'Domestic travel is about once every two months. Now, I plan to travel abroad at least once every two years.',
'I worry about safety when traveling.',
'I can\'t remember exactly, but it was a very good memory.',
'One month ago, I stayed in a hotel in Seoul',
'It was very boring',
);