var answer = answer.concat(
'This is a picture of a break room.',
'This is a picture of a outdoor market.',
'This is a picture of a pier / dock.',
'This is a picture of a construction site.',
'This is a picture of a (famous) tourist attraction.<br/>\
This picture shows a (famous) tourist attraction.',
'There are deserts in the display case.',
'There is a trash bin under the lamppost.',
'There is a customer at the counter.',
'There is a sales assistant behind the counter.',
'There are tress along the fence.',
'There is a table opposite the TV.',
'A man has gray hair.',
'A man has a mustache.',
'A man has short hair.',
'A man has a beard.',
'A woman has blond hiar.',
'A woman has curly hair.',
'A woman has pigtails.',
'A woman has a ponytail.',
'A woman is wearing a business suit.',
'A woman is wearing casual clothes.',
'Looking, Watching',
'Carrying',
'facing',
'reaching for',
'paying for',
'bending',
'shopping',
'relaxint, resting',
'crossing',
'kneeling down',
'In the middle of the picture, a man wearing glasses is  working on a computer. He has gray hair.',
'On the left side, there is another man talking on the phone. He is wearing a blue shirt.',
'On the right side of the picture, a woman in a white shirt is looking through a drawer.',
'In the background, I see some blinds closed over the window.',
'It seems like everyone in this picutre is quite busy.',
'work on a computer',
'type on a keyboard',
'look at a computer screen',
'talk on the phone',
'do some paperwork',
'have a meeting(conversation)',
'make copies',
'give a presentation(speech)',
'sit at desks in rows',
'explain something',
'point at something',
'turn pages of a book',
'take a book from the bookshelf',
'be hanging on the wall',
'be hanging from the ceiling',
'be standing along the wall',
'be arranged on a desk',
'be stacked on the floor',
'be attatched to the wall',
'be diveded by some partition walls',
'look very busy',
'look very friendly',
'look very focused',
'look very important',
'hand ~ some money',
'hold a plastic bag',
'look around',
'display something on a stand',
'weigh some food on a scale',
'pay at the counter',
'point at an item',
'pick out an item from the shelf',
'push a shopping cart',
'reach for an item',
'try on some shoes',
'wait for one\'s turn',
'take an order',
'have a meal at a table',
'serve food to a customer',
'wear an apron',
'look at the menu',
'be sitting in a cart(on a table)',
'be displayed on shelves(at a kiosk)',
'be decorated with plants',
'be hanging on racks',
'be set up in the store',
'be stacked on a shelf',
'be posted on a board',
'look like a popular place to visit',
'be well organized',
'look like a good place to shop',
'This is a picture of an outdoor cafe/restarant',
'There are 2 people sitting at a table',
'A man on the left is wearing a pink shirt and gesturing with his hand.',
'A woman in the middle is wearing a scarf and looking at the man.',
'They both have grey hair.',
'A woman standing on the right is wearing an apron and holding a pen and notepad.',
'She seems to be taking an order (= It seems like she is taking an order)',
'Every one is smiling (= All three of them have a smile on their faces)',
'So, it looks like they are having a good time',
'An old man has a big smile on his face',
'You have something on your nose / forehead',
'Do I have something in/between my teeth?',
'An old woman has a baby on her back',
'She has a run In her stocking',
'This picture shows a Cafe',
'A woman wearing a black apron is standing behind display cases.',
'She seems to be taing an order (= It seems like she\'s taking an order)',
'On the right side of the picture, a man in/wearing a green shirt is looking at the woman.',
'In the background, there are menu boards hanging on the wall. (= I see S + V)',
'The display cases look empty',
'It seems like all the food is sold out',
'ride a bicycle(motocycle)',
'walk on the sidewalk',
'carry a bag',
'pass by some stores',
'ask for directions',
'stand in a group',
'stand at a crosswalk',
'walk past',
'walking in the crosswalk',
'mapping the floor',
'sweep the streat',
'wait in a bus shelter',
'wait at a bus stop',
'pay for a ticket',
'stand at a ticket counter',
'leave(approach) the platform',
'come out of the station',
'come into the station',
'lean over a railing',
'get off the bus(train)',
'get on the bus(train)',
'wait in iline',
'wait for a bus(train)',
'get in the car',
'be approaching the station(bus stop)',
'be leaving the station(bus stop)',
'be parked along the street',
'be parked in a garage',
'be installed near a building entrance',
'be hanging on the side of a building',
'be under constrctuion',
'be at an intersection',
'be crowded with people',
'look like a famous tourist attraction',
'This is a picture of street',
'A lot of people are walking in the crosswalk in both directions',
'One of the men on the left is wearing a white shirt and carring a backpack',
'Near him, there is a woman walking with two bags',
'The traffic light looks white',
'In the background of the picture, I see many cars and buildings',
'This street looks very crowded with a lot of people',
'It seems like the downtown area of a big city',
'This is a picture of a bus stop',
'A bus is approaching the bus stop. (the platform)',
'Some people are standing in line to get on the bus',
'One of the man in line is holding a green plastic bag and another man behind him is standing up from a bench',
'I see a big picture on the bus shelter.',
'I think it is an advertisement for famous brand sungalss',
'Many trees are planted around the bus shelter and there is a white building (standing) in the background',
'This place is not crowded with many people and it doesn\'t look like a big city',
'Sit on a bench',
'Walk along a path',
'Walk a dog',
'Push a baby stroller',
'Pose for a picture',
'Water some flowers',
'Swim in the sea',
'sunbathe on a beach',
'lie under a beach umbrella',
'play in the sand',
'ride in a boat',
'paddle a boat',
'fish with a fishing rod',
'hike along a path',
'play a musical instrument',
'applaud for the performance',
'perform on a stage',
'sit in charis in rows',
'sing into a microphone',
'admire(looking) some artwork',
'watch a game in a stadium',
'be planted along a fence',
'be scattered along a beach',
'be tited to a pier',
'be floating in the water',
'look relaxed',
'look peaceful',
'be a beautiful day for a picnic',
'This is a picture of a beautiful park',
'Most of the people in this picture are sitting on benchs',
'On the right side of the picture, a man in a white shirt is sitting alone on a bench and another man is taking a picture of him',
'The man with the camera is wearing a blue hat and has a red jacket tied around his waist',
'And all the other people in this picture are sitting in pairs',
'In the foreground of the picture, there is a row of flowers. (=there are flowers planted in a row)',
'And most of the area in the park is covered in green grass <br/>\
- covered with : 살짝 <br/>\
- coverd in : 많이 ',
'This place looks very quiet and peaceful',
'This is a picture of a park',
'In the middle of the picture, there are some people standing in front of a big water fountain',
'They are posing for a picture',
'There is a group of women standing on the right side of the picture',
'One of them is holding a green umbrella',
'In the foreground, a man in a red shirt is carrying a bag and looking at the women',
'There is a huge tower and some trees in the water fountain',
'This place looks like a famous tourist attraction',
'This is a picture of a lot of people sitting or standing on outdoor steps',
'Some of the people in this picture are having a conversation with each other',
'Some other people are using their cell phones',
'In the middle of the picture, a man sitting on a bench is wearing an orange sleeveless shirt and beige shorts',
'He has shoulder length hair',
'And he seems to be reading something on his cell phone',
'It seems like this picture has been taken on a school campus',
'All the people in this picture look like college students',
'This is a picture of a pier',
'Most of the people in this picture are walking along the pier(in both directions)',
'The woman on the lfeft is leaning over the railing and seems to be looking at the sea',
'In the middle of the picture, another woman and a boy are holding their hands<br/>\
(=another woman is walking hand-in-hand with a boy)',
'On the right side of the picture, a man in a red shirt is holding a cup',
'I also see some people walking to the white building at the end of the peir',
'The sky looks clear and it is a beautiful sunny day',
'This is a picture of a park',
'In the middle of the picture, there is a group of 4 people',
'They look like a family',
'The father is holding a camera in his right hand and the mother is kneeling down on the gorund',
'Their two grils are standing near them',
'Behind the family, there is a woman holding onto a (baby) stroller',
'I also see some other groups of people around the park',
'On the right side of the picture, there  are beatuiful flowers planted in the center of the grass',
'There must be something intersting going on in the park because some of the people are looking to the left side of the picture',
'This is a picture of an office/ a lobby',
'There are four people sitting around a table',
'All of them are wearing suits',
'They seem to be having a meeting (= It seems like they\'re having a meeting)',
'The two men on the lfet are looking at a sort of a document',
'The two women on the right are looking at something together with their legs crossed',
'Behind those 4 people, there is a big white pole (=pillar) and some empty green chairs',
'It seems like people in this picture are quite busy',
'This is a picture of a bag store in a mall',
'Many colorful bags are displayed on the shelves and reacks',
'On the left side of the picture, there is a man carrying a backpack on his back <br/>\
(= Aman has a backpack on his back) ',
'He seems to be paying for something at the counter',
'Behind him, another man in red pants is looking around(=browsing) the store',
'In the foreground of the picture, two men wearing uniforms are passing by the store',
'This store looks modern and trendy',
'This is a picture of a street',
'I see lights from many stores and cars',
'In the foreground of the picture, some people are walking in the crosswalk in a line',
'They look blurry',
'They must be walking too fast (=It seems like thye are walking to fast)',
'I also see a man wearing a safety vest in the middle of the street',
'He seems to be directing the traffic',
'Next to him, a man on a bike is passing by and a black car is turning around the corner',
'Some cars are waiting for people to cross the street',
'This place looks very crowded with many people and cars',
'This convenince store is (just) around the corner',
'Christmas is just around the corner',

// Part 4
'It will (=is going to) be held at Bristol Convetion Center, and it will start at 9 in the morning on November 3rd',
'I think so, There will(=is going to) be a lunch break from noon to 2 P.M. so it won\'t be a problem to make a phone call then',
'Sure / Of course / Absolutely / Certainly ! <br/>\
First, he will (=is going to) lead a worshop on Private Water Coaching from 2 to 3 P.M.',
'Then, he will (=is going to) give a presentation on Programs for Restoring Muscles from 4 to 5 P.M.',
'Harris Park community Center is (located) at 110 Blue Parkway, and the summer program starts on Agust 1st',
'I\'m afraid not. Let me double check. No, It is 70 dollars for each class (=per class)',
'Sure/Of course/Absolutely/Certainly!',
'There are two classes that begin after 6 P.M.',
'One is Comic book illustrations, which is held from 6:30 to 8:30 P.M. every Tuesday (=On Tuesdays). The textbook will be provided',
'The other one is Swimming, and it is going to be held from 7 to 9 P.M. on Fridays',
'He is applying for a sales manager, and he wants to get paid 50,000 dollars a year',
'Yes, I think so. He took part in an internship program at River Plaza Hotel in France from 2006 to 2007, and he is fluent in French',
'Sure! He has worked at two different companies so far.',
'First, he worked at HACP Corporation as a sales representative from 2008 to 2012.',
'And then, he has been working at the Hudson Trade as an assistant sales manager since 2013',
'He is going to arrive in Seattle at 11:20 P.M. on May 29th',
'I\'m afraid not. According to his (=It says here on his) itinerary, he is supposed to take the Q-track train from Seattle King Station to Portland Union Station',
'Of course! He\'s going to stay at Portland Palace Hotel from May 30th to June 1st',
'He can check-in after 2 in the afternoon, and his check-out time has to be no later than 12 P.M. (=noon).',
'I mean, if he chekcs out later than 12, what he should know is (that) he will have to pay 10 dollars (= ther will be a 10 dollar late charge)',
'This interviews are going to be held in Conference Room B, and the first interviewee is Daniel Andreson',
'I\'m afraid not. Well, we were supposed to have 2 applicants for the editorial department',
'But, one of the interviews with Neil Wright has been cancelled',
'Absolutely! We have 2 applicants who have 6 years of experience',
'First, there will be an interview with Liam Moore at 2 P.M.',
'He is applying for a position in Marketing',
'After that, You are going to interview Emily Lewis at 3 P.M. ',
'She hopes to work in legal department',
'The interviews will be held in Room A, and the first one will start at 10 A.M.',
'I\'am afraid not. Well, there is only one interview for a spinning instructor position.',
'It\'s going to be with Janet Healy at 10:30 A.M.',
'Sure! There are 2 interviews for the personal trainer position.',
'First, ther will be an interview with Dana Carvey at 11 A.M.',
'She studied Sports Science',
'Second, we are going to interview Bill Nighy at 1 P.M.',
'According to his resume (=It says here on his resume), he can work only on weekends',
'We are at 415 Byrant Street, and we open at 11 A.M. everyday',
'I\'m afraid not. you\'re supposed to make a payment upon pickup.',
'Of course! He orderd a dozne of sunflowers for 70 dollars.',
'Also, he orderd 10 yellow roses and 15 daisies. They are 30 dollars and 37 dollars and 50 cents, respetively',
'So, it is 137 dollars and 50 cents in total (=the total is /comes to 137 dollars and 50 cents)',
'It is 20 dollars for each class (= per class)',
'I\'m arfaid not. Well, we have classes only on weekdays. (=There are classes only on weekdays = There are no classes on weekends)',
'Absolutely! There are two classes during your lunch break.',
'The first one is aerobics on Mondays(=very Monday) from 12 to 1 P.M., and it is going to be led by Barbara Berners',
'Also, ther is a Yoga class led by Chris Stark on Wednesday at the same time',
'He got (=earned = recived) his Bachelor\'s dgree in culinary arts from Boston University in 2013',
'Yes, I think so. Well, according to his resume(= it sayss here on his resume that), he has a certifgication in banking and pasrty',
'Certainly! First, he worked as an apprentice at Grill King Restaurant in Boston from 2013 to 2015',
'Also, he has been working as a line chef at Hotel Gresham in New York since 2016',
);