var answer = answer.concat(
'This is a picture of a break room.',
'This is a picture of a outdoork market.',
'This is a picture of a pier / dock.',
'This is a picture of a construction site.',
'This is a picture of a (famous) tourist attraction.<br/>\
This picture shows a (famous) tourist attraction.',
'There are deserts in the display case.',
'There is a trash bin under the lamppost.',
'There is a customer at the counter.',
'There is a sales assistant behind the counter.',
'There are tress along the fence.',
'There is a table opposite the TV.',
'A man has gray hair.',
'A man has a mustache.',
'A man has short hair.',
'A man has a beard.',
'A woman has blond hiar.',
'A woman has curly hair.',
'A woman has pigtails.',
'A woman has a ponytail.',
'A woman is wearing a business suit.',
'A woman is wearing casual clothes.',
'Looking, Watching',
'Carrying',
'facing',
'reaching for',
'paying for',
'bending',
'shopping',
'relaxint, resting',
'crossing',
'kneeling down',
'In the middle of the picture, a man wearing glasses is  working on a computer. He has gray hair.',
'On the left side, there is another man talking on the phone. He is wearing a blue shirt.',
'On the right side of the picture, a woman in a white shirt is looking through a drawer.',
'In the background, I see some blinds closed over the window.',
'It seems like everyone in this picutre is quite busy.',
'work on a computer',
'type on a keyboard',
'look at a computer screen',
'talk on the phone',
'do some paperwork',
'have a meeting(conversation)',
'make copies',
'give a presentation(speech)',
'sit at desks in rows',
'explain something',
'point at something',
'turn pages of a book',
'take a book from the bookshelf',
'be hanging on the wall',
'be hanging from the ceiling',
'be standing along the wall',
'be arranged on a desk',
'be stacked on the floor',
'be attatched to the wall',
'be diveded by some partition walls',
'look very busy',
'look very friendly',
'look very focused',
'look very important',
'hand ~ some money',
'hold a plastic bag',
'look around',
'display something on a stand',
'weigh some food on a scale',
'pay at the counter',
'point at an item',
'pick out an item form the shelf',
'push a shopping cart',
'reach for an item',
'try on some shoes',
'wait for one's turn',
'take an order',
'have a meal at a table',
'serve food to a customer',
'wear an apron',
'look at the menu',
'be sitting in a cart(on a table)',
'be displayed on shelves(at a kiosk)',
'be decorated with plants',
'be hanging on racks',
'be set up in the store',
'be stacked on a shelf',
'be posted on a board',
'look like a popular place to visit',
'be well organized',
'look like a good place to shop',
'This is a picture of an outdoor cafe/restarant',
'There are 2 people sitting at a table',
'A man on the left is wearing a pink shirt and gesturing with his hand.',
'A woman in the middle is wearing a scarf and looking at the man.',
'They both have grey hair.',
'A woman standing on the right is wearing an apron and holding a pen and notepad.',
'She seems to be taking an order (= It seems like she is taking an order)',
'Every one is smiling (= All three of them have a smile on their faces)',
'So, it looks like they are having a good time',
'An old man has a big smile on his face',
'You have something on your nose / forehead',
'Do I have something in/between my teeth?',
'An old woman has a baby on her back',
'She has a run In her stocking',
'This picture shows a Cafe',
'A woman wearing a black apron is standing behind display cases.',
'She seems to be taing an order (= It seems like she's taking an order)',
'On the right side of the picture, a man in/wearing a green shirt is looking at the woman.',
'In the background, there are menu boards hanging on the wall. (= I see S + V)',
'The display cases look empty',
'It seems like all the food is sold out',
'ride a bicycle(motocycle)',
'walk on the sidewalk',
'carry a bag',
'pass by some stores',
'ask for directions',
'stand in a group',
'stand at a crosswalk',
'walk past',
'walking in the crosswalk',
'mapping the floor',
'sweep the streat',
'wait in a bus shelter',
'wait at a bus stop',
'pay for a ticket',
'stand at a ticket counter',
'leave(approach) the platform',
'come out of the station',
'come into the station',
'lean over a railing',
'get off the bus(train)',
'get on the bus(train)',
'wait in iline',
'wait for a bus(train)',
'get in the car',
'be approaching the station(bus stop)',
'be leaving the station(bus stop)',
'be parked along the street',
'be parked in a garage',
'be installed near a building entrance',
'be hanging on the side of a building',
'be under constrctuion',
'be at an intersection',
'be crowded with people',
'look like a famous tourist attraction',
'This is a picture of street',
'A lot of people are walking in the crosswalk in both directions',
'One of the men on the left is wearing a white shirt and carring a backpack',
'Near him, there is a woman walking with two bags',
'The traffic light looks white',
'In the background of the picture, I see many cars and buildings',
'This street looks very crowded with a lot of people',
'It seems like the downtown area of a big city',
'This is a picture of a bus stop',
'A bus is approaching the bus stop. (the platform)',
'Some people are standing in line to get on the bus',
'One of the man in line is holding a green plastic bag and another man behind him is standing up from a bench',
);