var answer = answer.concat(
'relics',
'overaching',
'for the saking of',
'in compliance with',
'on-site',
'Korean National Folk Museum has a lot of things that cause notstalgia',
'If you want to visti, you need to reservation throguh the website.',
'Nostalgia means missing home.',
'Sometimes ancient relics are found at the costruction site.',
'I study hard with UPhone for the sake of speak like a native speaker.',
'Take your seat as quickly as possible.',
'I haven\'t been to the National Folk Museum.',
'It is very hard for me.',
'They were children.',
'do away with',
'roll out',
'affiliate',
'discountinued',
'This project is implemented in terms of sustainability.',
'Starbucks Korea will run a project called \"Better Together.\"',
'dairy',
'vowed',
'achiving',
'lid',
'If you bring back the token, you can get a deposit.',
'Rewards when you do not use diposable cups.',
'Sometimes I have to make important decision in my life.',
'I feel uncomfortable, but I think it\'s an action for the earth.',
'Education is seen as the key to success in Korean society.',
'Legally easy, culturally difficult.',
'There is no end to living while comparing.',
'The primary thing to take into account before tying the knot is their intent.',
'Their will is the main factor to consider when getting married.',
'I think many people delayed because of economic issueses.',
'I think for some people who prefer small weddings, it is an advantage for them.',
'I want many people to celebrate my wedding and congratulate us.',
'Less people came to my wedding.',
'Our country has many difficulties for young people.',
'Many peopler are despreate for their lives.',
'I got married last year.',
'I recently adjusted to a new workplace.',
'All creatures are beautiful.',
'Many cats can be seen on the street or our neighborhood.',
'Scientists conduct animal research to gather information.',
'Conserving water is important for the citizens.<br/>\
Conserving water is very crucial for the citizens.',
'Children\'s rights should be prioritized over parental rights to educate tehir children.',
'However, the committe conclude that the application contained excessive functions.',
'Recently, applications for violating children\'s rights were issued.',
'I\'m not on the same page with this opinion.',
'I\'ve been working for a public company for a year.',
'I think respecting children\'s basic right is very important.',
'Public companies are subject to almost all laws.',
'Many children have their own smartphones nowdays.',
'I can experience and learn various cultures aborad.',
'The end of the pandemic has caused a surge in travel.',
'We have to ramp up the airlines in my country, so I can easily go abroad.',
'I haven\'t been to those countries yet.',
'I just want to see the beautiful beaches abroad.',
'I want to visit a country that has beautiful beaches.',
'But flight company\'s economic condition still not good before pandemic.',
'Most people fly to Japan since it\'s close to Korea.',
'The reason for this phenomenon is the easing of social distancing rules.',
'I think it\'s all due to the abnormal atmosphere which causes very huge hurricanes and earthquakes.',
'Many people are saving water.',
'We started doing that in November last year.',
'Decrease the water pressure.',
'The city government recommended the people to use or consume smaller amount of water.',
'I try to reduce my outdoor activities.',
'One of the concern of people in our country is drought.',
'The problems of the Earth has been revealed now days.',
'I think global warming is serious nowdays.',
'I don\'t go hiking, but I often go to restaurants or cafes at the foot of the mountain.',
'Because the tourist attraction is closet to home.',
'I swim once every 2days.',
'These days, I\'m lazy, so I haven\'t climbed the mountain.',
'Climbing this mountain takes about 5~6 hours.',
'Nowdays, pamphlets are very beautiful.<br/>\
Advertisements today are highly attractive.',
'The Avengers\' story of collecting scatterd stones.',
'I think about two or three years ago I climbed the mountain in my country.',
'Nowdays, I don\'t climb mountains.',
'The spot is one of 100 tourist spots in my country.',
'Phamplet is contains tourist spot with public transportation and foreign languagues.',
'Some attractions have been selected six consencutive times since that list was launched.',
'Those who go high education people more easily get a chance to good company.',
'After listening to the opinions of my school teachers and parents, I decided on my major.',
'I hope that the entrance test will disappear and be replaced with a more creative curriculum.',
'mock exam',
'I messed up the entrance exam.',
'Popular departments are highly competitive, and those that are not are relatively easy.',
'The most important thing is the will of the students.',
'My parents assist me financially.',
'I can recall.',
'The test in our country is extremely challenging.',
'I belive that one\'s financial level is crucial.',
'A college degree affects the economic power. <br/>\
A college degree influences economic power.',
'My high school recommended that I choose my major.',
'Our country\'s test is competitive.',
'I think many living expenses, education items, and more activities need a lot of money.',
'On the other hand, the group that only listned to music showed enhanced abilities.',
'The process includes participants offering to learn five piano pieces.',
'According to research, learning to play musical instruments helps reduce stress, anxiety, and depression.',
'He is one of the most famous people in the world.',
'Exercise keeps my mind fast and active.',
'They were divided into three groups.',
'I agree with the script.',
'I have no questions.',
'My parents recommended learning to play the piano.',
'I learned to play the piano when I was about seven years old.',
'I have no talent for acting.',
'I know myself well.',
'Hapiness is living a normal life.',
'Because there is no insurance for pets in Korea, medical expenses are expensive.',
'Our company has numerous screens.',
'Almost everyone wishes for longevity and happiness.',
'The dog died because of a car accident.',
'It made me feel terrible inside.',
'When I was young, I got a small dog.',
'Koreans make up the majority of visitors to this country.',
'Where I live, there are many buses and subways.',
'If you come to Gwangju, I would like to intrudouce you to the city.',
'Gwangju is a city that is not well known to foreigners, but I was surprised to know.',
'The city I live in is less crowded than Seoul.',
'I tend to like lyrical tourism.',
'Seoul is good all year round, and Jeju Island is especially recommended to vist in summer.',
'If you want to experience the big city, I recommend Seoul, and if you want to enjoy nature, I recommended Jeju Island.',
'I ate local food and toured traditonal sights.',
'I think 3-5 days is appropriate.',
'I\'ve never had a longacation vacation.',
'My city is well-kown for its cultural events.',
'I think jeju Island is famous for all kinds of water sports.',
'If you were to ask me, I would say that I enjoy water sports like boating.',
'If a foreigner asks me what I would recommend, I\'d choose Seoul over Jeju Island.',
'Although Seoul is a city, you can enjoy traditonal attractions.',
'I went to Japan about three months ago.',
'I wish to go Vietnam because I got interested in the destination that the article introduced.',
'One out of every four.',
'I didn\'t find out, but it\'s in the article.',
'E-masks are significantly more expensive than regular masks.',
'I think this is a bit puzzling.',
'I\'m still learning, so I\'m not very good at it.',
'Since the corona virus has been around for a long time, I think masks are no longer needed.',
'Wearing a mask protexts against viruses as well as fine dust.',
'In my country, it is still necessary to wear face masks whenever you are inside an establishment.',
'It is hard to be close to people.',
'My workplace also requires us to wear a mask.',
'I don\'t agree with wearing a mask until now.<br/>\
I am currently opposed to the use of masks.',
'It is the best course of action for preventing viruses.<br/>\
It is the most effective strategy for avoding viruses.',
'It was very impressive.',
'Paper books makes me focous on reading more.<br/>\
Paper books encourage me to read more.',
'I usually read at lunch time.',
'When I haven\'t enough money I living uncanny condition.',
'The Harry Potter series was adapted into a movie.',
'I don\'t eat breakfast.',
'There are three rooms in my house.',
'I don\'t have to worry about the noise.',
'Seoul has the best facilities on Korea.',
'Global warming is a serious phenomenon.',
'The employees are hardworking.',
'I haven\'t been there.',
'I want to live in the USA,',
'Much money is required on taking care of pets.<br/>\
Pet care costs a lot of money.',
'I feel like I am in a good mood when I have pets at home.',
'It is good fight back loneliness.',
'I haven\'t had any experience owning a pet cat or dog.',
'I go shopping once a month on average.',
'Quality is more essential than quantity.',
'I\'m not good at fashion',
'According to the article, children\'s clothing has increased by 9.6 percent.',
'Friday is a more fun day compared to Sunday.',
'I usually shirt and slacks in weekdays.',
'Disruption in global supply chains and the consequent rise in costs are the reasons why price rise.',
'The Korean Statistical Information Service and the CPI Tell about the rise in prices.',
'Clothing prices have risen in a decade.',
'They recommend to maintain ear health our entire lives.',
'According to WHO, around 430 million people have hearing impariment.',
'Second, using earphones with high volume.',
'First, when they go to concerts.',
'Young people are exposed to high volume.',
'The article talks about the reality of using earphones and ear health.',
'I didn\'t adjust the earphone volume, but after reading this article, I think I should.',
'I use earphones when using public transportation.',
'Did you enjoyed Army?',
'One good thing is He don\'t go to the military.',
'The reason why He can\'t hear well is not because He listen to music loudly, but because of it.',
'My close fried is hard of hearing in one enar.',
'Because reading a book makes me feel smarter.',
'I try to read as many different books as possible.',
'Reading book is good to potential',
'It may take a little thought, but I think I\'ll get used to it again.',
'Thursday is the hardest.',
'Because driving is boring, listening to music can help I focus.',
'Because I am Christian, I love music made by Christians.',
'When I get more familiar with English, I will try that',
'I try to read a variety of books',
'It\'s great when there is a three-day holiday.',
'They are experiencing excessive workdays',
'Microwaves are hazardous to one\'s health',
'I like to listen to music.',
'I will put my phone on roaming during vaction, so I can easily contact my family.',
'I will use the Agoda app to book accommodation.',
'I often buy souvenirs that can only be bought at tourist spots.',
'I went for a day trip.',
'I have lived in this house for over 30 years, so I get along well with my neighbors in the neighborhood.',
'In an apartment, many families live in one building, but in a detached house, only one family lives.',
'I linve in a detached house.',
'house : building / home : live',
'I go to work in the office',
'It was very tiring.',
'Yesterday, I went  on a business trip.<br/>\
I traveled for business yesterday.',
'Gwangju is the iste of the 2002 world Cup quarter-final match beteween Korea and Spain.',
'It\'s not a very famous place, how do you know?',
'I haven\'t been there.',
'I don\'t know some of the details.',
'Gwangju city is located on the southern part of South korea.',
'For me, when I want to visit the beach, Jeju island is the place in my country.',
'I\'m planning to go on a trip in the Philippines.',
'A car acts as a big bag.',
'It is inconvenient to use public transportation when I have a lot of luggage.',
'It has taken up to 1 hour and 30 minutes during heavy snowfall.',
'Where I live, rush hour is 8 A.M. and 6 P.M.',
'I like to arrive early.',
'I\'m not familiar with shortcuts.',
'I was attended my friend\'s wedding',
'Are you still recounting the horrible memories I mentioned earlier?',
'I thought leaving 30 minutes earlier would be enough, but I didn\'t think the parking lot would be crowded.',
'All of the cars were like turtles.',
'I didn\'t think of finding a parking lot.',
'I am not often late because I like to leave early.',
'Because missing the train was my fault.',
'The taxi driver knows a shortcut.',
'The speaker is late for his flight so he took a taxi',
'I think being a punctual person is very important.',
'It is also a good habit to pack your luggage in advance if possible.',
'Of course. I hate the thought of being late for work.',
'I opt for 6 a.m. since I want to evate traffic congestion.',
'I gave solutions to my customers.<br/>\
I provided my clients solutions.',
'Those shoes were cheap, not expensive.<br/>\
Those shoes were not pricey; they were inexpensive.',
'I prefer to buy in an offline shop.',
'If I bought shoes in an offline shop, I think it would only take one or two days.',
'I use to buy masks and other necessities online.',
'I bought shoes on internet.',
'I want their diffuser, but it is not for sale; anyway, when I can afford it, I wish to go ther again.',
'There are amenity-minded employees who are accommodating, and the design is very cool; furthermore, the place has a cozy smell.',
'The Paradise Hotel in Busan was the best hotel.',
'I don\'t pack well because I don\'t like the garbage that comes from delivery food.',
'Because I can eat fresh food right away.',
'I don\'t order appetizers or desserts seperately.',
'Our country is illegal smoke in side of restaurant.',
'I can barely make simple food like fried eggs or ramen.',
'I am not good at food.',
'I like to eat light food.',
'What can I get you?',
'Follow me to your table, please.',
'I usually eat in restaurants with my wife.',
'I can enjoy enough delicious food within the corporate card limit.',
'Corporate cards have a limit of thrity thousand won per person.',
'Eating out with my boss is a little inconvenient, but essential for my work life.',
'I reserve a lunch restaurant for a meal with my boss.',
'I\'d like to reserve a table at your restaurant next Sunday night.',
'I usually reserve by phone.',
'It is paid for by the company.',
'I have been working for my current company for about eight years.',
'I prefer to be an employee than have my own business.',
'Receiving a salary is more stable than running a business.',
'He wants to book for next Sunday.',
'I haven\'nt thought of running my own restaurant.',
'They have a hard time moving in the plane. <br/><br/>\
They have a struggle moving in the plane.',
'shoulders are heavy.',
'I was planning to go next year, but it seems difficult because I expecting a baby.',
'I took a knife to cut the fruit.',
'I accidentally got on a plane with a knife.',
'설날 means the first day of the new year in the lunar calendar.',
'I don\'t have a winter vacation.',
'It was because the distances of the destinations were a bit far.',
'I traveled for a total of 4 days, 2 days in Gyeongju and 2 days in Busan, and moved from place to place every day.',
'I had a domestic travel.',
'Yes I saw the video.',
'When we notified them about our honeymoon, they prepared wine for us.',
'I\'ve tired both over the phone and online. I prefer online because it\'s cheap.',
'But after calling serveral times, the guesthouse owner canceled it for free.',
'At first, the guesthouse owner did not cancel free of charge and demanded a penalty fee.',
'I wanted a single room, but I accidentally booked a guesthouse and canceled it.',
'At that time, I was too lazy to call, so I just went inside the blanket.',
'The hotel I stayed in when I was on a business trip a few days ago was a bit cold.',
'I think the cleanliness of the hotel is the most important.',
'The travel agency booked both the hotel and the plane.',
'I took a day off to travel to Japan.',
'I need to apply for a vacation to the company to go to Japan.',
'We are going on a package tour, so the travel agency will tafke care of everything.',
'We are ready for the trip.',
'I\'m having trouble sleeping.',
'After this class, I will have breakfast.',
'They provide free breakfast.<br/>\
They offer complimentary breakfast.',
'I went on a business trip and flew a drone.',
'I stayed at a hotel tow days ago.',
'He checks out on Sudnay.',
'I\'m a sociable person, so I like to hang out with other people wherever I go.',
'I want to go to Hawaii for my honeymoon, but I couldn\'t because of my job change schedule.',
'I don\'t speak Japnese at all.',
'When I travel, I don\'t spare money on food.',
'I like Japense ramen the most.',
'I want to eat Japanese food, vist traditonal Japanes tourist spots, and experience Japanes hot springs.',
'My wife wants to go on a pre-birth trip to Japan.',
'I\'m planning to go to Japan on my next vacation. 2 weeks later',
'I\'m not sure, but the price of a hotel in Seoul is about 10 million won per night',
'You can only reserve a double room.',
'I was just busy.',
'The hotel was very clean and satisfactory.',
'When I choose a hotel, price is my top priority, so I don\'t think service is very important.',
'I took classes for 6 days over 2 weeks.',
'I live close to my relatives.',
'I see them every two to three months.',
'get away',
'on tap',
'Because of COVID-19, We couldn\'t go on my honeymoon properly.',
'I remember my trip Thailand on a shor-term misson',
'If I had to choose just one of these, I would like to go to Jeju Island. Because there are various summer tourist attractions here.',
'I have been to Thailand only.',
'What\'s your plan for this summer?',
'I think its\'s better to be far away for a while',
'I wasn\'t able to go abroad on my honeymoon because of COVID-19',
'We first visited traditional attractions',
'No, I don\'t live in Seoul',
'I want to go there and enjoy Leisure activites',
'It can help me get away from work',
'We went on our honeymoon to Gyeongju and Busan',
'I didn\'t live in Jeju Island, I just went for sightseeing',
'Halla Mountain is easy to climb because it has a gentle slope, but the course is very long',
'I have never been to Canada or Mexico <br/>\
I\'ve never set foot in Canada or Mexico',
'My trip to Thailand is very secure',
'I didn\'t visit Hawaii',
'Domestic travel is about once every two months. Now, I plan to travel abroad at least once every two years.',
'I worry about safety when traveling.',
'I can\'t remember exactly, but it was a very good memory.',
'One month ago, I stayed in a hotel in Seoul',
'It was very boring',
);