var answer = answer.concat(
'I live close to my relatives.',
'I see them every two to three months.',
'get away',
'on tap',
'Because of COVID-19, We couldn\'t go on my honeymoon properly.',
'I remember my trip Thailand on a shor-term misson',
'If I had to choose just one of these, I would like to go to Jeju Island. Because there are various summer tourist attractions here.',
'I have been to Thailand only.',
'What\'s your plan for this summer?',
'I think its\'s better to be far away for a while',
'I wasn\'t able to go abroad on my honeymoon because of COVID-19',
'We first visited traditional attractions',
'No, I don\'t live in Seoul',
'I want to go there and enjoy Leisure activites',
'It can help me get away from work',
'We went on our honeymoon to Gyeongju and Busan',
'I didn\'t live in Jeju Island, I just went for sightseeing',
'Halla Mountain is easy to climb because it has a gentle slope, but the course is very long',
);