var answer = answer.concat(
'Advance registration is 80 dollars and same-day registration is 90 dollars',
'It won\'t be a problem at all. The conference will start at 9:30 A.M., so you won\'t miss anything',
'Sure, Alan Forrester will lead two sessions at the conference',
'First, he will give a lecture titled "Know Your Audience" at 10 A.M. on May 16th.',
'Second, he will lead a workshop on "branding Strategies" at 3:30 P.M. on May 17th',
'If I had a job interview, I\'d bring in a portfolio of my work',
'I think it\'s better to show my work samples rather than try to describe them',
'I\'d prefer a job interview in person',
'I think body language and facial expressions play an important role in communication.',
'They would help me to show the interviewer how confident I am',
'Also, I\'d want to meet my potential futuer boss and co-workers in person and get a feel for the workplace',
'I think this picture was taken in an office',
'A man is sitting at a desk and talking on the phone.',
'He is wearing a dark green shirt and glasses',
'Next to him, a woman is laening over the desk and turning a page in a big file folder',
'She seems to be helping the man find some information',
'I can see a computer on the desk and some filing cabinets in the background',
'This office look very bright because of the ligth coming through the big windows',
'I don\'t think that schools should schedule time each day for students to participate in outdoor activities',
'Of course, students need outdoor activities',
'Many outdoor activites are healthy, and they can help relieve stress',
'However, there are some disadvantages of having these activities evrery day',
'First, not every student is eager to participate in outdoor activities.',
'Some students are not good at sports and feel stressed when they have to take part in outdoor activities',
'Secondly, if students participate in outdoor activites every day, they will probably use up their energy and then feel exhuasted',
'So, the outdoor activites may distract students from their studies and even cause injuries',
'Therfore, I don\'t think that schools should require students to participate in outdoor activities each day',
'This is a picture of four people in a waiting area',
'Two people on the right are sitting in armchairs and talking on the phone',
'There are both wearing glasses',
'On the left, two women are having a conversation',
'One of them is sitting in an armchair holding some documents, and the other is looking at the documents over her shoulder',
'I can see a potted plant and a small table on the carpeted floor',
'All the people look relaxed',
'My mother usually cooks in my house and she cooks for us almost every day',
'I really appreciate it and try to help her',
'The last time I used the Internet to look up a food recipe was last Saturday',
'I found a recipe for spaghetti on someons\'s blog and it was easy to follow',
'Yes, I\'d consider taking a cooking course online.',
'It would be nice to take each lesson step by step and complete the course at my own pace',
'Also, it would be more convenient than coing all the way to school to take a course',
'Your first activity is to atten the breakfast for new employees in the conference room and it will start at 9 A.M.',
'Let me see. It looks like there was a lunch scheduled with Mr. Kim, but that lunch was canceled. It is rescheduled for November 21st',
'Sure, you need to finish the budget report between 9:30 and 10 A.M. and e-mail it to the director by 10 A.M.',
'Also, thre will be a budget discussion with the director in the meeting room B at 3 P.M.',
'First, you have to sign up for a new e-mail account',
'We need someone who is proficient with computers',
'It is easier to compare prices online',
'I spend one or two hours managing my blog every day',
'News is updated online in real time',
'You can get the most up-to-date inofrmation on jobs',
'An electronic navigation devices is built in to a car',
'We\'d better send a mass e-mail to all employees',
'It helps you access the Internet easily',
'We will deonstrate how to set up your new printer',
'Please reamin on the line and we will assist you soon',
'A new smartphone has great features',
'People recycle palstic items, paper and bottles',
'They sepearte the garbage at home or at work',
'We have to encourage people to choose environment-friendly products',
'You should place different waste materials in each seperate bag',
'We can save natural resources',
'Alternative energy sources are very important to our country',
'I think they should install soundproof walls',
'I\'d like to live in the countryside when I\'m retired',
'We should conserve wildlife to save our planet',
'Yellow dust has caused a lot of damage',
'The company is trying to reduce environmental pollution',
'I always choose organic ingredients',
'Hello, this is Shawn returning your call',
'Hello, this is Justin Noth calling about the new employees',
'Welcome to the Wild Bear Tour',
'Thank you for calling the Norton Art Center',
'Please call me back and let me know what you think',
'If you have any questions, feel free to call me back',
'This is all for today\'s show',
'Have a nice time during your stay here',
'We would really appreciate your business',
'There is some free time from 3:00 to 4:00 P.M.',
'There will be a speech by David Austin',
'We are taking a tour from 1:00 to 2:00 P.M.',
'We are offering free samples of our new product',
'I\'ll introduce the advantages of this system to all of you',
'Let me introduce your team leaders',
'We are proud to have Laura Kim here with us today',
'I\'m really sorry for the inconvenience we caused',
'I apologize for the delay',
'I must apologize for our misunderstanding of the iussue',
'I feel sorry for the problem you\'ve been through',
'I deeply reget that I cannot attend your seminar',
'I\'m sorry that we haven\'t been returning your messages',
'May I suggest you bring your own laptop?',
'I suggest (that) you call a staff meeting tomorrow',
'Please consider which one to buy',
'We\'d better put a notice about this on the office board',
'Why don\'t we put an advertisement about this on the Internet?',
'Let\'s buy more copieers for our employees',
'Please make sure (that) you have all of your belonging with you',
'Don\'t forget to vist the produce section',
'Don\'t miss this opportunity to save up to 15%',
'Please double check the seat number on your ticket',
'Come and join our dance classes',
'I recommend making reservation in advance',
'I\'ll send a mass text message to all staff members',
'I\'m thinking of visiting my friend this Thursday night',
'I decided to show new employees around the company',
'I\'ll try to deliver a new box of paper on time',
'You are supposed to have dinner with your clients at 6',
'He is scheduled to give a presentation at 4.',
'I will see if I can arrange a video cnverence with them',
'The budget plan is due on Februrary 28th',
'You have to return them back by this Friday',
'you had better check other places and find a cheaper one',
'You should share idease with other co-workers',
'You need to attend the meeting at 3 tomorrrow',
'Why don\'t you go to the factory and find out what\'s happening ther?',
'I agree with this statement',
'I agree that it\'s getting hard for people to find jobs',
'Yes, I think that parents should spend good quality time with tehir children',
'I believe that it is better for students to go overseas to study',
'I disagree with this statement',
'I disagree that it\'s easy for companies to attract new customers',
'No, Idon\'t agree with this tatement',
'I don\'t think that young people spend a lot of money on entertainment',
'On the other hand, advertisements are not alwyas telling the truth',
'I would like to talk about it with Mr. Argos',
'I hope to hear good news from them',
'Let me know if you have any other suggestions',
'I prefer buses to trains because they are cheaper',
'I would rather get a bonus than have a vacation',
'If I could go abroad, I would go to Europe',
'In my opinion, having a pet can increase happiness',
'I think it\'s better if there is more public transporaotion in my neighborbood',
'It is not a good idea to increase our price of products',
'It would be great if I could make enough money to support my family',
'From my experience, I learned that first impressions are very important',
'Here\'s what I think',
'I\'ll tell you why I prefer to buy products online',
'There\'s no other flower shop like Amy\'s',
'I\'m sure that you can get a bonus check by the end of this month',
'It is true that this event will bring lots of new customers to our business',
'This is a good chance to show our new products to potential customers',
'I\'ll make sure that all employees are aware of this issue',
'There are some resasons to support my opinion',
'It\'s because the company disappointed us serveral times',
'The reason is (that) we have to cancel the sipping date',
'I heard that the new system is not working well',
'Since I\'m good at taking pictures, I like to take photographs of the palces I visit',
'It seems like a big opportunity for us',
'It seems like they are having a meeting',
'It seems that we need a backup plan for the problem',
'It is likely to reduce our profits this year',
'It appeaers to be floating on the water',
'The movie was not as exciting as the trailer of the movie',
'It\'s better to get information from the Itnernet than from books',
'Face to face learning is the most effective way to train employees',
'My hapiness is more improtant than anything else',
'Comapred with people in the past, people today spend less time with their family',
'Anyone can leave a comment online',
'The new conference room is bigger than the old one',
'Speaking a foreign language is the best qualification for this job',
'Shopping online has more advantages than sopping at a store',
'One of the advantages is that we can keep in touch with people online',
'There are some disadvantages of going abroad to study',
'The best thing about living in a big city is a variety of jobs',
'Honesty is his strong point',
'The weakest point of the new mobile phone is that ist bends in a pocket',
'There aer always pros and cons about issues',
'I think they want to choose which food do you want',
'The wall is surrounded by orange color',
'And overall it seems like a typical restaurant',
'She is looking for food, she wants to eat',
'This picture seems to be taken at some kind of an event',
'He is also holding a dish, and he also seems to be deciding which food he would like to take',
'So I guess the two people will get the food they want from this event',
'She is holding a dish, and she seems to be choosing which food to eat',
'I often go out to see musicians, about twice a week',
'I go out to see musicians perform live, at least once a year. The last time I went was last summer',
'The price is quite reasonable, and you can love it',
'So you can try to buy tickets',
'You can buy local conert tickets online. I guess they are pretty expensive, because they tend to be about a hundred and ten tounsand won',
'It will last one hour',
'Sonia Pinto will bel giving a lecture from eleven to noon ans also from three to four P.M.',
'At eleven A.M., she\'ll be giving a lecture about small business adverising tips',
'Family members are sitting around the table',
'They are having a meal',
'A big TV is hanging on the wall',
'Books are reflected in the mirror',
'A laptop is on top of the bookcase',
'I visit my younger sister in New York once a year',
'As far as I remember, my father bought me my first bike',
'I don\'t have time to visit my parents, let alone my friends',
'All bookcases are filled with many books',
'My older sister does house cores',
'I don\'t like doing the dises',
'I would rather stay at home than go out',
'I am grateful to my family for helping me succeed',
'Are you in need of financial support from your parents?',
'She is tied up with house chores on weekends',
'Children under 7 should be accompanied by parents',
'We have a conversation in a coffee shop',
'I need to lose weight for my health',
'I\'ve gained some weight during my vacation',
'There are many ways to get rid of stress',
'We\'d like to apologize for the inconvenience',
'Please be aware of safety regulations',
'I go to a hair salon to get my hair done',
'Cars are moving in the same direction',
'There is a traffic sign at the end of the street',
'Three people are crossing the street',
'My family gets together in the living room every night',
'We had fun at the party last night',
'I don\'t feel good and I need to go to see a doctor',
'The concert will take place at the world Stadium',
'All attendees are supposed to buy tickets',
'I participate in the festival every year',
'I usually spare some time to work out at a gym',
'The man in the middle is singing into a microphone',
'Some people are taking pictures of flowers',
'It\'s good chance to socialize with instructors',
'It takes some time for us to get to know each other',
'I went to see a movie with my friends',
'There are many tourist attractions in my city',
'I arranged a rental car at the airport',
'Let\'s go on a trip for a week',
'He\'ll fly with Northeast Airline No. 737',
'This is an all-inclusive trip without any extra cost',
'Flights are faster than trains, so we can save time',
'She is holding onto a shopping cart',
'We have to chip in some money to buy him a present',
'We\'d better hand out free samples in fornt of our store',
'Please visit us during regular business hours',
'Our store sells a wide range of furniture',
'You can try our new product for free',
'The market is always crowded with many customers',
'She is picking out some fruits',
'We have to consider their individual tastes',
'Sorry it is temporaily out of stock',
'You can save up to 20% off from this special deal',
'All items are 10% off the regular price',
'As compensation, we will send you an e-gift card online',
'I\'ll send it back to you by express delivery',
'Take this opportunity of free trial service this month',
'Some people are wating in line at the coutner',
'We should offer store points to our regular customers',
'I usually shop for clothes online',
'Earn points whenver you shop at our store',
'Ordering food online is better than over the phone',
'it dosen\'t take up much space',
'I\'ll go to your store to pick up my order',
'The restaurant is under renovation',
'I made a reservation for two at 7 P.M.',
'Sorry, we are overbooked on June 25.',
'My friends like eating out for dinner',
'She is holding a drink',
'I use a credit card because I don\'t carry cash with me',
'When looking into it, you can find what a problem is',
'She is taking notes on a piece of paper',
'We offer a variety of continuing education programs',
'My work is related to my major',
'I\'ll look up the word in the online dictionary',
'She is flipping through the book',
'Academic performance is not the key to success in life',
'Local school children will show off their singing skills',
'I\'m honored to speak on behalf of a ll students here',
'I\'m interested in foreign languages',
'It is better for some students to go overseas to study',
'Only a few students registered for the class',
'School uniforms give students a sense of belonging',
'Please call me back as soon as possible',
'Sometimes, customers are disappointed at our service',
'Please feel free to ask me (at) any time',
'Due to our tight budget, we will reduce travel expenses',
'All employees have to pass through the security desk',
'Before we make a decision, we need to discuss it',
'They are busy preparing for the workshop',
'To be exact, we\'ll hire 28 new employees',
'I work 9 to 5 expect for a lunch break',
'The system is no longer available in our office',
'You have to get along well with your co-workers',
'It is good for your business',
'I still keep in touch with my old customers',
'All companies must keep up with new market trends',
'All employees are required to submit sales reports today',
'The package will be delivered in time',
'We gieve a bonus based on employees\' work performance',
'She is applying for a marketing manger position',
'We will start the project at the begining of next month',
'Please hand in your paper no later than May 7.',
'He is one of my business associates',
'Please come up with some ideas about this issue',
'Can I take a day off tomorrow?',
'Don\'t worry about it. I\'ll take care of it',
'My assistant will take over my job next week',
'We\'d better hire 2 temporary employees',
'It\'s good for our tight budget',
'I\'ll take on the project right away',
'We should ask employees to do overtime',
'Hurry up or we\'ll be behind schedule',
'On-site training is better than online training',
'It\'s important to deliver our product in a timely manner',
'First of all, we will vist the facory on Mapole Street',
'I prefer a high-paying job to an interesting job',
'I don\'t surf the Internet at work',
'We can rearrange staff\'s schedule for work productivity',
'You asked me how to deal with this problem',
'Please call someone who is responsible for this',
'Let\'s take a short break',
'Face-to-face communication is better than e-mail',
'You can take advantage of all opportunities',
'They lost all data about clients by accident',
'The company is well known for its great customer service',
'Our gym members use a locker at no fee',
'We suggest you make a reservation 3 days in advance',
'Our representative will be in contact with you shortly',
'Let\'s go over the issues on the agenda',
'There will be an opening speech at 10 A.M.',
'The welcome speech will be presented by Mr. Hopes',
'The event will be followed by a coffe break',
'I\'d like to introduce Mr. Howard prior to the meeting',
'We\'ll have a guest speaker for our event',
'I\'m sorry but I have to leave in the middle of the event',
'Mr. Swindle is giving a presentation after lunch',
'We are planning to hold a big promotional event',
'We need catering service for our event',
'Compared to the last meeting, we have fewer complaints',
'I\'m in charge of scheduling rooms for events',
'Let\'s have a meeting for vote for the best manger',

// Part 6
'do house chores',
'intrests',
'keep in shape',
'have fun with',
'pay by credit card',
'go abroad',
'public transportation',
'have something delivered',
'read reviews',
'living expenses',
'save time and money',
'by myself',
'eat out, go out to eat',
'get rid of[relieve] stress',
'make new friends',
'attend a class',
'after-school activities',
'transfer to',
'wear a school uniform',
'earn credits',
'get instant feedback',
'take a course online',
'graduate student',
'have a part-time job',
'participate[take part] in',
'pay tution (fees)',
'register for ~ classes',
'study in a foreign country',
'physical exercise',
'imporve one\'s skills',
'job requirements',
'work-related',
'applicant',
'supervisor',
'qualifications for the job',
'be suitable for',
'work(ing) hours',
'be skilled at',
'flexible work shcedule',
'interpersonal skills',
'open(-plan) office',
'take a day off',
'experienced worker',
'get promoted',
'a long coummute',
'go on a business trip',
'benefits',
'deal with problems',
'a high-paying[well-paid] job',
'co-workes, colleagues',
'work efficiently',
'compete with',
'attract more customers',
'imporve[increase] productivity',
'share ideas online',
'look ~ up on the Internet',
'get access to ',
'send a text message to ~, text ~',
'update one\'s status',
'video chat, make a video call',
'be addicted to social media',
'write[post] a comment',
'digital devices',
'upload picture and videos',
'telecommuting, working from home',
'technical problem',
'surf the Internet',
'advances in technology',
'sacrifice time',
'serve the public',
'celebrities',
'public policy',
'be a role model to[for]',
'make a donation',
'have an influence on',
'renewable resources',
'pros and cons',
'recycle',
'city council',
'climate changes',
'prohibit, ban',
'live[go] green',
'volunteer',
'pollution',
'community service',
'eco-friendly',
'I think communication skills are the most important skills for a manage to have',
'That\'s because, first of all, good communication skills are necessary when giving feedback to employees on their performance',
'If a manage provides clear and constructive feedback, employees will be albe to make a better performance',
'Also, a manger with effective communcation skills can make the working atomsphere a lot better',
'In my case, my manager at work always tries to listen to the team members\' voices to make quick and better decisions',
'Therefore, I think communication skills are the most important skills for a manger to have',
'I agree that open-plan offices increase productivity',
'That\'s becuase, first of all, employees can easily talk about work and collaborate with each other in such an evironment (=in an environment like that)',
'In mycase, it has been beneficial to work in an open-plan office.',
'I can share ideas with my colleagues and ask them for help without (even) leaving my seat',
'This makes it much easier for us to save time and effor to achieve our common golas',
'Therefore, I strongly agree that open-plan offices increase productivity',
'People tend to meet up more often with friends who share their interests',
'If you and your friends have nothing in common, you might not want to spend much time with them',
'I can get honest opinions from people who have actually used the product',
'When buying clothes, I read customer reviews because they help me to choos the right size',
'It costs less than having my own car',
'I agree that common intrests are important ina friendship',
'I rely most on customer reviews',
'I prefer using public transportation',
'If I had a car, I would have to pay for the car itself, insurance, gas and more',
'Using public transport helps to reduce traffic and air pollution',
'Yes, I would do it with my friends',
'We would be able to enjoy our hobby and have fun together at the same time',
'By sharing a new hobby, we can get to know each other better and strength our bond',
'Pets make great companions, so you won\'t feel lonely',
'Raising a pet can help you develop a sense of responsibility',
'I think there are some benefists of having a pet',
'First of all, pets make great companions (=can be good friends), so you\'ll nvere feel lonely if you hav one',
'They will alway (be there to) welcome you home and keep you company after a long(= toguh) day',
'Second (of all), raising a pet can help you be more resposible',
'If you have a pet, you will (get to = be able to) learn how to take care of another living creature',
'This is especially good for children because it will help them develop a sense of responsibility',
'Therefore, I think it would be a good idea to have a pet (= it would be benificial to have a pet)',
'I agree that having vending machines in school benefits tudents',
'Studetns can get food or drinks when they need energy',
'Schools can make some profits and use the money to benefit students.',
'For example, they can invest in school facilities',
'I think computer lessons would be most beneficial for students',
'Computer skills are essential for success in their studies or future careers',
'I learned basic computer skills such as word processing at high school',
'They were very useful when doing my assignments at university',
'It\'s better to do an internship',
'Internship programs help students choose the right career path',
'Students can gain valuable work experience',
'This will be a great advantage when they apply for a job, because many companies prefer candidates with work experience',
'If I could make one change to the education system of my country, I would increase the time allocated for physical education in schools',
'Regular sports activities help students stay healthy',
'Also, students can reduce stress and anxiety by taking part in physical activities',
'It\'s not easy to focous on the lessons, bcause there are many distractions like social media',
'There is no face-to-face interaction with a teacher, So it\'s impossible to get instant feedback',
'I think it\'s better (OR a better way) for a university student to do an internship to spend a long vacation',
'That\'s because, first of all, I think internship programs help students choos the right career path',
'While they are taking part in the programs, they will be able to find out what they want to do, what they are good at or even what they are capable of',
'Also, I am sure that students will be able to have valuable work experience (in the field the\'re interested in.)',
'This will be a great advantage when they apply for a job since many companies prefer candidates with work experience',
'Therefore, I think doing an internship is a better way for a university student to spend a long vacation',
'Yes, I think companies should be allow their employees to have a flexible work schedule',
'Employees can choose to work during their most productive hours.',
'They will be able to work more efficiently',
'Employees can achieve better work-life balance',
'This will increase their level of job satisfaction',
'Workload is most important to me',
'It has a significiant influence on my job satisfaction',
'At my previous job, I had to work a lot of overtime, because we were understaffed',
'But the management didn\'t want to hire more staff, so I decided to leave',
'I would rather ahve a well-paid job even if i\'s bring',
'Money is the main reason why I work',
'If I receive a high salary, I won\'t have to worry about financial problems',
'If I were running my own store, I would ask customers for reviews of my products and services',
'I could learn what my customers really want and imporve my products and services based on their feedback',
'If I show them I care about their opinions, they will visit my store mor often',
'It\'s difficult to get decisions made',
'If you want to suggest an idea, you need to follow complex procedures',
'It takes a long time to reach agreements',
'I\'m in a team of 15 people, and every time ther\'s an issue, I have to sit through endless meetings',
'I think companies should allow their employees to have a flexible work schedule',
'That\'s because, first of all, if employees get to have flexible working hours, they will be able to work during their most productive hours',
'I mean, they will bel able to work more efficiently and make a better performance',
'Also, I\', sure that employees will be able to have better work-life balance',
'So, they won\'t have to worry about missing out on family life',
'In the long run, I believe flexible work shcedule will be beneficial on both sides, companies and employees',
'Therefore, I think companies should allow their empoyees to have a flexible work schedule',
'I disagree that the benefits of technology outweigh whte disadvantages',
'Adavnces in technology have had a negative impact on the environment',
'More and more people have becom addicted to technology',
'I think the best way to get news is by using the Internet',
'I can read news articles on my mobile phone anywhere if there\'s an Internet connection',
'It is the fastest, the most convenient way to learn about current affaris',
'Many people write comments on online articles, and these help me see both suides of the story',
'I prefer to shop online',
'I can place an order write just one click, so it takes less time',
'I don\'t have to walk aorund a store and wait in line at the checkout',
'I can buy goods at cheaper prices on the Internet',
'Yes, I would consider using this kind of mobile app',
'In fact, I\'ve used one before, and it was very conveient.',
'The app I used offered a variety of search and filtering options',
'It was easy to find a studio apartment near my work',
'You can send the same message to many people at once',
'E-mails you send or receive are stored automatically, so you can refer to them whenver you want',
'I think the best way to get news is using the internet',
'That\'s because, first of all, it is the fastest and the most conveinet way to learn about current affairs.',
'I mean, I can read news aritcles on my mobile phone anywhere if there is an internet connection',
'Also, many people today wirte comments on online articles, and these help me see both sides of the story.',
'I enjoy reading those comments because I can learn more from the story',
'Therfore/So, I think using the internet is the best way to get news',
'I agree that celebrities have a responsibility to be positive role models for children',
'Celebrities can have a big influence on children who look up to them',
'Childern tend to imitate their role models, from the way they look to the way they behave',
'I think my city should invest the most in green spaces such as parks',
'My city is full of buildings and cars, so we need more places to enjoy nature',
'I want to work as a volunteer at an animal shelter',
'Green spaces will imporve our well-being and quality of life in the long run',
'I ehard there are many animals in need of help but most animal shelters are short of volunteers',
'Helping out rescued animals is emotionally rewarding, and I can see the rsults of my work almost instantly',
'Spending time with animals is good for my physical and mental health',
'If my country wanted to impose a penalty on people for not recycling',
'We should protect the environment, so recycling should be mandatory',
'If there were penalties for not recycling, people would pay more attention',
'More people can enagage in cultural activites and have interesting experiences',
'It enriches our society',
'There is a park with public artwork in my area, and I often go there with my family',
'I can see beautiful pieces of art without having to buy tickets or dress up',
'If my country wanted to impose a penalty on people for not recycling, I would support that plan',
'That\'s because, first of all, I belive that we have to protect the environment, so recycling has to be mandatory (=compulsory)',
'Since pollution levels are getting higher these days, I think the governmnet has to take strong action to reduce the pollution',
'Also, if there were penalties such as fines for not recycling, I guess people would pay more attention on this matter',
'Therefore/So, if my country wanted to impose a penalty on people for not recycling, I would definitely support that plan',
'I think it\'s better to move frequently and live in different places',
'That\'s because, first of all, I think you will be able to broaden your mind by living in different parts of the world.',
'I mean, it will give you chances to learn other languages and cultures',
'Also, you will get to know a lot of new people and learn how to adjust yourself to new environments',
'In my case, I had a chance to live in XXX for a year and I learned a lot form that experience.',
'If i hadn\'t had that experience, I guess I wouldn\'t be able to speak English the way I speak now',
'Therefore/So, I think it\'s better to move frequently or live in different places',
'Yes, I think parents should help their children choose a field of study',
'That\'s because, first of all, most parents know what their kids are intrested in, what they are good at, and even what they are capable of.',
'In my case, when I was in my teens, my parents knew that I really enjoyed playing with computers.',
'One day, they convinced me to study computer science in college, which now I think was a great choice',
'Thanks to their excellent advice, I won\'t have to worry about getting a job in taht field',
'Therefore, I think parents should help their children choose a field of study',
'I agree that, in most jobs, people get more satisfaction from doing what they love (than from receving a high salary)',
'That\'s because, first of all, if people do what they love todo, I\'m sure that they will be able to focus on their work with more passion(=enthusiasm)',
'I mean, it is really important to find the right job that makes them happy doing it.',
'Also, I know some people who chose job to get paid well. Guess What?',
'Most of them ended up getting stuck in a rut and regretting making the wrong decision',
'Therefore/So, I strongly agree that, in most jobs, people get more satisfaction from doing what they love than from receiving a hihg salary',
'I think there are several advantages of using social media as a marketing tool',
'First of all, It is cost-effective.',
'I mean, you can make an account for free on most social media',
'Also, it is not that hard to increase your business reputation on social media',
'It means that you can easily be exposed to potential customers as well as your existing customers',
'Therfore/So, I think it is beneficial (=a good idea) to use social media as a marketing tool',
'I think there are some advantages of reading customer reviews when deciding which producs to buy',
'First of all, if you read other customers\' reviews, I bet it will be easier to get useful information about the products you are intrested in (getting).',
'I mean, you can save time and effort without doing any legwork',
'Also, you can get honest opinions from people who have already used the products',
'I mean, customers\' reviews are more reliable than any other kind of advertisements',
'In my case, once, I was really disaoointed with the product I recevied because it looked way different from the pictures in the advertisement',
'I guess it wouldn\'t\'ve happend if I had read customers\' reviews carefully before I made a purchase',
'Therefore/So, I think it is a good idea to read a lot of customers\' reviews when deciding whcih products to buy',

// Part 3
'I go out of the office and take short walk',
'And you get to know the stories behind them',
'Also, they help sellers and buyers reach a deal they are both happy with',
'In addition, products made of recycled materials are cheaper than those made of new materials',
'Besides, I could donate not only money but also used books or computers',
'I have a puppy myself and I consider him a family memer',
'Most students feel stressed because of their studies, and it is important for them to relieve stress',
'It takes about 10 minutes to get to the nearest station from my home',
'I can walk there. So, It\'s quite convenient',
'It is (only) about a 10 minute walk to the nearst station from my home. So, It\'s quite convenient',
'I usually buy train tickets online',
'By doing so, I can save time and effort since I don\'t have to wait in line at a ticket counter',
'The last time I went on a vaction was last year',
'I visited my sister in Seattle and stayed there for a week (and a half)',
'I went to Pusan with my closest friend. We went shopping, swimming and enjoyed eating a lot of fresh seafood there',
'I would consider using a travel agency for my trip because it would be convenient',
'I wouldn\'t consider using travel agency for my next trip',
'That\'s because it\'s easier to book trips online.',
'Also, I can easily get tons of travel information on the internet',
'easy to find useful information online(job openingsm, working conditions)',
'effectively collaborate with my colleagues, aks them for help',
'learn about teamwork',
'help each other to achieve our company\'s goals',
'like movies that my friends recommend',
'get faster responses from them',
'When I have an important issue, I usually talk on the phone',
'usually upload a few pictures',
'I prefer to talk with people during breaks at work',
'Actually, I like to enjoy my break time chatting with my colleagues.',
'They are all kind and friendly, so I quite like them',
'Yeah, I would consider working from home.',
'That\'s because I wouldn\'t have to commute to work (=travel to work)',
'look up the recipes on the Internet',
'have a sandwich for lunch and cookies for dessert',
'After trying a new restaurant, I share my review on soncial media',
'feel less bored',
'If I get a job in 2 or 3 years, I\'ll find a place near my company',
'picke up from the dumpsters behind my apartment building',
'The last time I cooked was last Friday, and I made some side dishes.',
'I looked up the recipes online, and they were easy to follow',
'The food I made was/tasted really good',
'Yeah, I would suggest that people take a bus to get around my city',
'That\'s because there are a lot of bus lines and they are well oragnized',
'save money if I work out in a park',
'should be close to my place so that I can go there regularly',
'use other facilities such as a copy machine or group study rooms',
'I\'m worried that they may not be getting enough water',
'Comedies make me laugh a lot, so I think watching them is a good way to relieve stress',
'I wouldn\'t go aborad if I could only take a few days off and didn\'t have much money',
'It would be a conveient way to look around the city, because it would take me to major tourist attractions',
'I enjoy looking at the twinkling lights of nighttime festivals',
'No, I don\'t go to the gym regulary.',
'I usually work out at the park.',
'That\'s because I like to get some fresh air and enjoy the beautiful nature (while exercising)',
'No, I\'ve never read a book in a cafe.',
'That\'s because it is hard for me to focus on reading (in such a place with some noise)',
'I like to read in a quiet room or library',
'fun to see interesting items that I can\'t find at retail stores',
'They have a large selection of items that come in different sizes and colors',
'I can even use my credit card',
'got it at a discount price',
'I get disappointed when the item arrives and doesn\'t look goon on me',
'These kinds of sales promotions would be the most effective ways to attract customers',
'I took him to a big toy store in a shopping mall and let him choose what he wanted',
'I think it\'s a practical gift because the receivers can use it to buy what they actually need',
'Gift wrapping usually doesn\'t cost much, and the store can do a better job',
'I guess I shop online at least once a week',
'I usually buy groceries or clothing online because most online stores offer products a tlower prices, (which I think is great)',
'I prefer to buy clothes in-store.',
'That\'s because I want to try them on before making a purchase',
'The other day, I bought a jacket online, but I got (sort of) upset because it didn\'t really look good on me)',
'I\'m sort of tiered / bored',
'It suits you well / It fits you well',
'I often download movies to my laptop, so I\'d choose the provider that offeres the fastest internet service',
'Also, I could access them from anywhere',
'I like streaming music, watching online videos, and playing mobile games',
'I recently got a new phone with a lot of storage space, so I downloaded many songs',
'I\', currently paying about 40 dollars per month, and i think that is reasonalbe',
'Smartphones have great vuilt-in cameras. I think they coul replace digital cameras',
'Products from top brands are usually expensive, but it\'s worth paying more, because the quality is good',
'She always does some research on the Internet and selects a product that has received good reviews',
'When I shop for electronics, I always do some online research first',
'Also, I try to read many reviews (= as many reviews as possible) before making up my mind (= making a decision)',
'Other than making phone calls or texting, i frequently read news articles or even stream music on my phone',
'Also, on the weekends, I watch some movies on Netfilx',
'I live in an apartment in xx with my family. We have lived there for 12 years',
'Out apartment is cozy, byut not spacious enough for my family',
'If I coul change one thing about my home, it would be the size',
'That\'s because I want to invite guests quite often. (So, I wish I lived in a bigger place)',
'I think I buy at least 12 to 15 books a year. I mean, I get at least a book a month',
'I usually buy books online because I can get them at lower prices <br/>\
(= because the prices are (a tad) lower than getting them at bookstores)',
'I guess I spend at least an hour (on) reading a day. So that makes at least 7 hours a week',
'Before I go to bed, I usually do my reading for a good night sleep',
'Most shops in my area are generally open from 10 A.M to 9 P.M.',
'But all the conveience stores are open 24 hours',
'Lotte Department Store is a good place to shop for gifts in my area',
'That\'s becuse it\'s pretty close to my house (= where I live). It\'s only about a five minute walk',
'Yes, I have bought a lot of e-books instead of paper books becuase they are cheaper than paper books',
'What I like best about reading e-book is that they can be stored on my phone and I can read them anytime',
'Also I don\'t need to worry about carrying heavy paper books',
'From my school, I get to the nearest place that serves breakfast on foot <br/>\
(= I walk to the nearest place that serves breakfast) ',
'There is a nice brunch restaruant near my school(work place). It\'s only about a 10 minute walk (to get there)',
'Yes, I often buy coffe while I am at scool/work.',
'That\'s because I sometimes get sleepy after lunch and I can stay awake with some coffe/caffeine',
'(Well, I don\'t know the exact number, but) <br/>\
I guess more than five hundered thousand travelers visit my city every year.',
'That\'s because there are a lot of famous tourist attractions in my city',
'There is an official website. And you can find information about my city there',
'There is an official website where you can find information about my city (in advance)',
'Also, there are several tourist information centers in downtown area',
'I work out at the gym every (other) day. And I try to work out at least an hour and a half each time I go there',
'I usually walk fast on a treadmill.',
'Also, I do resistance training for an hour to stay in good shape',
'It was last summer. I took an English conversation class and I really had a lot of fun with the teacher and classmates',
'The subject I (really) liked in school (= my favorit subject in school) was Korean History',
'The teacher was so inspiring and engaging',
'I guess my favorite room in my home is the living room',
'That\'s because, it\'s not that big, but we have a nice comfortable sofa to sit on',
'Also, my family can gather around together and have quality family time there',
'I read more now than I did in the past. (I read less in the past than I do now)',
'That\'s because, I have to do more reading for my position at school / work',
'(I mean,) I used to read novels for pleasure, but now I have to read a lot of news or thesis related articles',
'I think you should buy a mug for your dad since he loves drinking coffee',
'Also, why don\'t you get some cosmetics for your mom for her skin care',
'And how about getting some fridge magnets for yourself. Those will bring back some good memories',
'For me, I think a smartphone is the best device for reading e-books.',
'That\'s because, smartphones today have larver storage space to download many e-books',
'Also, I can read them anytime and anywhere with my smartphone <br/>\
So, I think the best device for reading e-books is a smartphone',
'If you were going to take a friend out for lunch, I would recommend (taking him / her to) one of the most famous Italian restaurants near my workplace/school',
'That\'s because, for me, I love the place in that the food is really good and the price is quite reasonable (Also, I love the cozy atmosphere)',
'except that',
'I really like that girl except that she is always splurging on something',
'It\'s really har to pick just one because there are so many popular tourit attractions in my city. But, if I had to choose one, xxx would be the most popular place to visit.',
'That\'s because that place has a lot of things to see, and there are tons of things to do there',
'When I decide on a gym, I think a convenient location is the most important to me.',
'That\'s because, it was a bit far from my home',
'So, guess what? I skipped exercising quite often',
'But, the gym now I work out at is withn a stone\'s throw, and I\'ve never skipped woring out there',
'I think xx University is the best one in my area',
'That\'s because, it\'s a well-known national university',
'Also, the tution of the school is a lot cheaper than people think',
'The school always offers high quality courses as well.',
'So, I think the best university in my area is xx University',

// Part 2
'This is a picture of a break room.',
'This is a picture of a outdoor market.',
'This is a picture of a pier / dock.',
'This is a picture of a construction site.',
'This is a picture of a (famous) tourist attraction.<br/>\
This picture shows a (famous) tourist attraction.',
'There are deserts in the display case.',
'There is a trash bin under the lamppost.',
'There is a customer at the counter.',
'There is a sales assistant behind the counter.',
'There are tress along the fence.',
'There is a table opposite the TV.',
'A man has gray hair.',
'A man has a mustache.',
'A man has short hair.',
'A man has a beard.',
'A woman has blond hiar.',
'A woman has curly hair.',
'A woman has pigtails.',
'A woman has a ponytail.',
'A woman is wearing a business suit.',
'A woman is wearing casual clothes.',
'Looking, Watching',
'Carrying',
'facing',
'reaching for',
'paying for',
'bending',
'shopping',
'relaxing, resting',
'crossing',
'kneeling down',
'In the middle of the picture, a man wearing glasses is  working on a computer. He has gray hair.',
'On the left side, there is another man talking on the phone. He is wearing a blue shirt.',
'On the right side of the picture, a woman in a white shirt is looking through a drawer.',
'In the background, I see some blinds closed over the window.',
'It seems like everyone in this picutre is quite busy.',
'work on a computer',
'type on a keyboard',
'look at a computer screen',
'talk on the phone',
'do some paperwork',
'have a meeting(conversation)',
'make copies',
'give a presentation(speech)',
'sit at desks in rows',
'explain something',
'point at something',
'turn pages of a book',
'take a book from the bookshelf',
'be hanging on the wall',
'be hanging from the ceiling',
'be standing along the wall',
'be arranged on a desk',
'be stacked on the floor',
'be attatched to the wall',
'be diveded by some partition walls',
'look very busy',
'look very friendly',
'look very focused',
'look very important',
'hand ~ some money',
'hold a plastic bag',
'look around',
'display something on a stand',
'weigh some food on a scale',
'pay at the counter',
'point at an item',
'pick out an item from the shelf',
'push a shopping cart',
'reach for an item',
'try on some shoes',
'wait for one\'s turn',
'take an order',
'have a meal at a table',
'serve food to a customer',
'wear an apron',
'look at the menu',
'be sitting in a cart(on a table)',
'be displayed on shelves(at a kiosk)',
'be decorated with plants',
'be hanging on racks',
'be set up in the store',
'be stacked on a shelf',
'be posted on a board',
'look like a popular place to visit',
'be well organized',
'look like a good place to shop',
'This is a picture of an outdoor cafe/restarant',
'There are 2 people sitting at a table',
'A man on the left is wearing a pink shirt and gesturing with his hand.',
'A woman in the middle is wearing a scarf and looking at the man.',
'They both have grey hair.',
'A woman standing on the right is wearing an apron and holding a pen and notepad.',
'She seems to be taking an order (= It seems like she is taking an order)',
'Every one is smiling (= All three of them have a smile on their faces)',
'So, it looks like they are having a good time',
'An old man has a big smile on his face',
'You have something on your nose / forehead',
'Do I have something in/between my teeth?',
'An old woman has a baby on her back',
'She has a run In her stocking',
'This picture shows a Cafe',
'A woman wearing a black apron is standing behind display cases.',
'She seems to be taing an order (= It seems like she\'s taking an order)',
'On the right side of the picture, a man in/wearing a green shirt is looking at the woman.',
'In the background, there are menu boards hanging on the wall. (= I see S + V)',
'The display cases look empty',
'It seems like all the food is sold out',
'ride a bicycle(motocycle)',
'walk on the sidewalk',
'carry a bag',
'pass by some stores',
'ask for directions',
'stand in a group',
'stand at a crosswalk',
'walk past',
'walking in the crosswalk',
'mapping the floor',
'sweep the streat',
'wait in a bus shelter',
'wait at a bus stop',
'pay for a ticket',
'stand at a ticket counter',
'leave(approach) the platform',
'come out of the station',
'come into the station',
'lean over a railing',
'get off the bus(train)',
'get on the bus(train)',
'wait in iline',
'wait for a bus(train)',
'get in the car',
'be approaching the station(bus stop)',
'be leaving the station(bus stop)',
'be parked along the street',
'be parked in a garage',
'be installed near a building entrance',
'be hanging on the side of a building',
'be under constrctuion',
'be at an intersection',
'be crowded with people',
'look like a famous tourist attraction',
'This is a picture of street',
'A lot of people are walking in the crosswalk in both directions',
'One of the men on the left is wearing a white shirt and carring a backpack',
'Near him, there is a woman walking with two bags',
'The traffic light looks white',
'In the background of the picture, I see many cars and buildings',
'This street looks very crowded with a lot of people',
'It seems like the downtown area of a big city',
'This is a picture of a bus stop',
'A bus is approaching the bus stop. (the platform)',
'Some people are standing in line to get on the bus',
'One of the man in line is holding a green plastic bag and another man behind him is standing up from a bench',
'I see a big picture on the bus shelter.',
'I think it is an advertisement for famous brand sungalss',
'Many trees are planted around the bus shelter and there is a white building (standing) in the background',
'This place is not crowded with many people and it doesn\'t look like a big city',
'Sit on a bench',
'Walk along a path',
'Walk a dog',
'Push a baby stroller',
'Pose for a picture',
'Water some flowers',
'Swim in the sea',
'sunbathe on a beach',
'lie under a beach umbrella',
'play in the sand',
'ride in a boat',
'paddle a boat',
'fish with a fishing rod',
'hike along a path',
'play a musical instrument',
'applaud for the performance',
'perform on a stage',
'sit in charis in rows',
'sing into a microphone',
'admire(looking) some artwork',
'watch a game in a stadium',
'be planted along a fence',
'be scattered along a beach',
'be tited to a pier',
'be floating in the water',
'look relaxed',
'look peaceful',
'be a beautiful day for a picnic',
'This is a picture of a beautiful park',
'Most of the people in this picture are sitting on benchs',
'On the right side of the picture, a man in a white shirt is sitting alone on a bench and another man is taking a picture of him',
'The man with the camera is wearing a blue hat and has a red jacket tied around his waist',
'And all the other people in this picture are sitting in pairs',
'In the foreground of the picture, there is a row of flowers. (=there are flowers planted in a row)',
'And most of the area in the park is covered in green grass <br/>\
- covered with : 살짝 <br/>\
- coverd in : 많이 ',
'This place looks very quiet and peaceful',
'This is a picture of a park',
'In the middle of the picture, there are some people standing in front of a big water fountain',
'They are posing for a picture',
'There is a group of women standing on the right side of the picture',
'One of them is holding a green umbrella',
'In the foreground, a man in a red shirt is carrying a bag and looking at the women',
'There is a huge tower and some trees in the water fountain',
'This place looks like a famous tourist attraction',
'This is a picture of a lot of people sitting or standing on outdoor steps',
'Some of the people in this picture are having a conversation with each other',
'Some other people are using their cell phones',
'In the middle of the picture, a man sitting on a bench is wearing an orange sleeveless shirt and beige shorts',
'He has shoulder length hair',
'And he seems to be reading something on his cell phone',
'It seems like this picture has been taken on a school campus',
'All the people in this picture look like college students',
'This is a picture of a pier',
'Most of the people in this picture are walking along the pier(in both directions)',
'The woman on the lfeft is leaning over the railing and seems to be looking at the sea',
'In the middle of the picture, another woman and a boy are holding their hands<br/>\
(=another woman is walking hand-in-hand with a boy)',
'On the right side of the picture, a man in a red shirt is holding a cup',
'I also see some people walking to the white building at the end of the peir',
'The sky looks clear and it is a beautiful sunny day',
'This is a picture of a park',
'In the middle of the picture, there is a group of 4 people',
'They look like a family',
'The father is holding a camera in his right hand and the mother is kneeling down on the gorund',
'Their two grils are standing near them',
'Behind the family, there is a woman holding onto a (baby) stroller',
'I also see some other groups of people around the park',
'On the right side of the picture, there  are beatuiful flowers planted in the center of the grass',
'There must be something intersting going on in the park because some of the people are looking to the left side of the picture',
'This is a picture of an office/ a lobby',
'There are four people sitting around a table',
'All of them are wearing suits',
'They seem to be having a meeting (= It seems like they\'re having a meeting)',
'The two men on the lfet are looking at a sort of a document',
'The two women on the right are looking at something together with their legs crossed',
'Behind those 4 people, there is a big white pole (=pillar) and some empty green chairs',
'It seems like people in this picture are quite busy',
'This is a picture of a bag store in a mall',
'Many colorful bags are displayed on the shelves and reacks',
'On the left side of the picture, there is a man carrying a backpack on his back <br/>\
(= Aman has a backpack on his back) ',
'He seems to be paying for something at the counter',
'Behind him, another man in red pants is looking around(=browsing) the store',
'In the foreground of the picture, two men wearing uniforms are passing by the store',
'This store looks modern and trendy',
'This is a picture of a street',
'I see lights from many stores and cars',
'In the foreground of the picture, some people are walking in the crosswalk in a line',
'They look blurry',
'They must be walking too fast (=It seems like thye are walking to fast)',
'I also see a man wearing a safety vest in the middle of the street',
'He seems to be directing the traffic',
'Next to him, a man on a bike is passing by and a black car is turning around the corner',
'Some cars are waiting for people to cross the street',
'This place looks very crowded with many people and cars',
'This convenince store is (just) around the corner',
'Christmas is just around the corner',

// Part 4
'It will (=is going to) be held at Bristol Convetion Center, and it will start at 9 in the morning on November 3rd',
'I think so, There will(=is going to) be a lunch break from noon to 2 P.M. so it won\'t be a problem to make a phone call then',
'Sure / Of course / Absolutely / Certainly ! <br/>\
First, he will (=is going to) lead a worshop on Private Water Coaching from 2 to 3 P.M.',
'Then, he will (=is going to) give a presentation on Programs for Restoring Muscles from 4 to 5 P.M.',
'Harris Park community Center is (located) at 110 Blue Parkway, and the summer program starts on Agust 1st',
'I\'m afraid not. Let me double check. No, It is 70 dollars for each class (=per class)',
'Sure/Of course/Absolutely/Certainly!',
'There are two classes that begin after 6 P.M.',
'One is Comic book illustrations, which is held from 6:30 to 8:30 P.M. every Tuesday (=On Tuesdays). The textbook will be provided',
'The other one is Swimming, and it is going to be held from 7 to 9 P.M. on Fridays',
'He is applying for a sales manager, and he wants to get paid 50,000 dollars a year',
'Yes, I think so. He took part in an internship program at River Plaza Hotel in France from 2006 to 2007, and he is fluent in French',
'Sure! He has worked at two different companies so far.',
'First, he worked at HACP Corporation as a sales representative from 2008 to 2012.',
'And then, he has been working at the Hudson Trade as an assistant sales manager since 2013',
'He is going to arrive in Seattle at 11:20 P.M. on May 29th',
'I\'m afraid not. According to his (=It says here on his) itinerary, he is supposed to take the Q-track train from Seattle King Station to Portland Union Station',
'Of course! He\'s going to stay at Portland Palace Hotel from May 30th to June 1st',
'He can check-in after 2 in the afternoon, and his check-out time has to be no later than 12 P.M. (=noon).',
'I mean, if he chekcs out later than 12, what he should know is (that) he will have to pay 10 dollars (= ther will be a 10 dollar late charge)',
'This interviews are going to be held in Conference Room B, and the first interviewee is Daniel Andreson',
'I\'m afraid not. Well, we were supposed to have 2 applicants for the editorial department',
'But, one of the interviews with Neil Wright has been cancelled',
'Absolutely! We have 2 applicants who have 6 years of experience',
'First, there will be an interview with Liam Moore at 2 P.M.',
'He is applying for a position in Marketing',
'After that, You are going to interview Emily Lewis at 3 P.M. ',
'She hopes to work in legal department',
'The interviews will be held in Room A, and the first one will start at 10 A.M.',
'I\'am afraid not. Well, there is only one interview for a spinning instructor position.',
'It\'s going to be with Janet Healy at 10:30 A.M.',
'Sure! There are 2 interviews for the personal trainer position.',
'First, ther will be an interview with Dana Carvey at 11 A.M.',
'She studied Sports Science',
'Second, we are going to interview Bill Nighy at 1 P.M.',
'According to his resume (=It says here on his resume), he can work only on weekends',
'We are at 415 Byrant Street, and we open at 11 A.M. everyday',
'I\'m afraid not. you\'re supposed to make a payment upon pickup.',
'Of course! He orderd a dozne of sunflowers for 70 dollars.',
'Also, he orderd 10 yellow roses and 15 daisies. They are 30 dollars and 37 dollars and 50 cents, respetively',
'So, it is 137 dollars and 50 cents in total (=the total is /comes to 137 dollars and 50 cents)',
'It is 20 dollars for each class (= per class)',
'I\'m arfaid not. Well, we have classes only on weekdays. (=There are classes only on weekdays = There are no classes on weekends)',
'Absolutely! There are two classes during your lunch break.',
'The first one is aerobics on Mondays(=very Monday) from 12 to 1 P.M., and it is going to be led by Barbara Berners',
'Also, ther is a Yoga class led by Chris Stark on Wednesday at the same time',
'He got (=earned = recived) his Bachelor\'s dgree in culinary arts from Boston University in 2013',
'Yes, I think so. Well, according to his resume(= it sayss here on his resume that), he has a certifgication in banking and pasrty',
'Certainly! First, he worked as an apprentice at Grill King Restaurant in Boston from 2013 to 2015',
'Also, he has been working as a line chef at Hotel Gresham in New York since 2016',
);